server:
  port: 8083

spring:
  application:
    name: API-Gateway-Service
  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path= /user/**
        - id: Department-Service
          uri: lb://Department-Service
          predicates:
            - Path= /department/**



eureka:
  cleint:
    registerWithEureka: 'true'
    fetchRegistry: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

